# X-AnyLabeling 🌟, AGPL-3.0 license

name: 🚀 Feature Request
description: Request a new feature
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a X-AnyLabeling 🚀 Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
      placeholder: |
        What new feature would you like to see in X-AnyLabeling?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share? What did you expect?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/CVHub520/X-AnyLabeling/pulls) (PR) to help improve X-AnyLabeling for everyone, especially if you have a good understanding of how to implement a feature.
      options:
        - label: Yes I'd like to help by submitting a PR!