# X-AnyLabeling 🌟, AGPL-3.0 license

name: 🎰 Model Request
description: Request support for a new model to be added to X-AnyLabeling
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a X-AnyLabeling 🎰 Model Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the X-AnyLabeling [model_zoo](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/model_zoo.md) to see if a model request already exists.
      options:
        - label: >
            I have searched the X-AnyLabeling [model_zoo](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/model_zoo.md) and found no similar model requests.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your model.
      placeholder: |
        What new model would you like to see in X-AnyLabeling?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your model request. It will help us understand and prioritize the model request.
      placeholder: |
        How would this model be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share? What did you expect?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/CVHub520/X-AnyLabeling/pulls) (PR) to help improve X-AnyLabeling for everyone, especially if you have a good understanding of how to implement a new model.
      options:
        - label: Yes I'd like to help by submitting a PR!