# X-AnyLabeling 🌟, AGPL-3.0 license

blank_issues_enabled: true
contact_links:
  - name: 📃 Docs
    url: https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/
    about: Full X-AnyLabeling Documentation